# Artificial Neural Network

### Importing the libraries

In [87]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

In [4]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [6]:
x = dataset.iloc[:, 3:-1].values

In [7]:
y = dataset.iloc[:, -1].values

In [8]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [9]:
print(y)


[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [10]:
le = LabelEncoder()

In [11]:
x[:, 2] = le.fit_transform(x[:, 2])

In [12]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [13]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')

In [14]:
x = np.array(ct.fit_transform(x))

In [15]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [17]:
print('Split x train: ', x_train)
print('Split x test: ', x_test)
print('Split y train: ', y_train)
print('Split x test: ', y_test)

Split x train:  [[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]
Split x test:  [[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]
Split y train:  [0 0 0 ... 0 0 1]
Split x test:  [0 1 0 ... 0 0 0]


### Feature Scaling

In [18]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
print('Scaling x train: ', x_train)
print('Scaling x test: ', x_test)

Scaling x train:  [[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]
Scaling x test:  [[-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
   1.62185911]
 [ 1.04501206 -0.61433742 -0.57427105 ...  0.66011376 -1.02429504
   0.504204  ]
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376 -1.02429504
   0.72775202]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
  -1.54162886]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376 -1.02429504

## Part 2 - Building the ANN

### Initializing the ANN

In [19]:
ann = tf.keras.models.Sequential()
ann

### Adding the input layer and the first hidden layer

In [20]:
hidden_neuron_unit_layers = 6
output_neuron_unit_layers = 1
activation_function = 'relu'
activation_function_probability = 'sigmoid'


ann.add(tf.keras.layers.Dense(units=hidden_neuron_unit_layers, activation=activation_function))

### Adding the second hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=hidden_neuron_unit_layers, activation=activation_function))

### Adding the output layer

In [22]:
ann.add(tf.keras.layers.Dense(units=output_neuron_unit_layers, activation=activation_function_probability))


## Part 3 - Training the ANN

### Compiling the ANN

In [23]:
optimizer_function = 'adam'
loss_function = 'binary_crossentropy'
neuron_metrics = ['accuracy']

ann.compile(optimizer=optimizer_function, loss=loss_function, metrics=neuron_metrics)

### Training the ANN on the Training set

In [24]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 536us/step - loss: 0.6630 - accuracy: 0.6260
Epoch 2/100
250/250 [==============================] - 0s 516us/step - loss: 0.4802 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 517us/step - loss: 0.4447 - accuracy: 0.7971
Epoch 4/100
250/250 [==============================] - 0s 578us/step - loss: 0.4314 - accuracy: 0.8018
Epoch 5/100
250/250 [==============================] - 0s 511us/step - loss: 0.4241 - accuracy: 0.8120
Epoch 6/100
250/250 [==============================] - 0s 511us/step - loss: 0.4177 - accuracy: 0.8183
Epoch 7/100
250/250 [==============================] - 0s 513us/step - loss: 0.4117 - accuracy: 0.8215
Epoch 8/100
250/250 [==============================] - 0s 508us/step - loss: 0.4054 - accuracy: 0.8260
Epoch 9/100
250/250 [==============================] - 0s 510us/step - loss: 0.4002 - accuracy: 0.8278
Epoch 10/100
250/250 [==============================] - 0s 518us/step - l

250/250 [==============================] - 0s 520us/step - loss: 0.3348 - accuracy: 0.8635
Epoch 80/100
250/250 [==============================] - 0s 573us/step - loss: 0.3353 - accuracy: 0.8631
Epoch 81/100
250/250 [==============================] - 0s 509us/step - loss: 0.3355 - accuracy: 0.8616
Epoch 82/100
250/250 [==============================] - 0s 515us/step - loss: 0.3348 - accuracy: 0.8626
Epoch 83/100
250/250 [==============================] - 0s 517us/step - loss: 0.3355 - accuracy: 0.8636
Epoch 84/100
250/250 [==============================] - 0s 518us/step - loss: 0.3352 - accuracy: 0.8636
Epoch 85/100
250/250 [==============================] - 0s 519us/step - loss: 0.3349 - accuracy: 0.8633
Epoch 86/100
250/250 [==============================] - 0s 514us/step - loss: 0.3352 - accuracy: 0.8634
Epoch 87/100
250/250 [==============================] - 0s 513us/step - loss: 0.3350 - accuracy: 0.8635
Epoch 88/100
250/250 [==============================] - 0s 522us/step - loss:

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [68]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [86]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [88]:
cm = confusion_matrix(y_test, y_pred)

In [89]:
print(cm)

[[1537   58]
 [ 210  195]]


In [90]:
ac_score = accuracy_score(y_test, y_pred)

In [91]:
print(ac_score)

0.866
